"""empty message

Revision ID: 217fb261db18
Revises: 3a24472d1754
Create Date: 2021-04-08 04:39:35.010164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217fb261db18'
down_revision = '3a24472d1754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'usuarios', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'username')
    # ### end Alembic commands ###
